SELECT * FROM(SELECT DISTINCT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC,CITY ASC) WHERE ROWNUM=1;

SELECT * FROM(SELECT DISTINCT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC,CITY DESC) WHERE ROWNUM=1;
